// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: 172x320

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_lblTopLeft = NULL;lv_obj_t *ui_lblBottomRight = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Screen1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblTopLeft = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lblTopLeft, lv_pct(100));
lv_obj_set_height( ui_lblTopLeft, LV_SIZE_CONTENT);   /// 1
lv_label_set_text(ui_lblTopLeft,"Starting...");

ui_lblBottomRight = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lblBottomRight, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblBottomRight, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lblBottomRight, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_lblBottomRight,"NO NETWORK");
lv_obj_set_style_text_color(ui_lblBottomRight, lv_color_hex(0x800000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblBottomRight, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblBottomRight, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblBottomRight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblBottomRight, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblBottomRight, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblBottomRight, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblBottomRight, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblBottomRight, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_lblTopLeft= NULL;
ui_lblBottomRight= NULL;

}
