// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: 172x320

#ifndef _UI_SCREEN1_H
#define _UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_lblTopLeft;
extern lv_obj_t *ui_lblBottomRight;

void ui_Screen1_screen_init(void);
void ui_Screen1_screen_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
